# Render deployment trigger
services:
  - type: web
    name: 17-web-culinary-discovery
    env: static
    buildCommand: npm run build
    publishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 22
